create table COCKTAIL_SHOPPING_LIST
(
    COCKTAIL_ID UUID,
    SHOPPING_LIST_ID UUID,
    FOREIGN KEY (COCKTAIL_ID) references COCKTAIL(ID),
    FOREIGN KEY (SHOPPING_LIST_ID) references SHOPPING_LIST(ID),
    PRIMARY KEY (COCKTAIL_ID, SHOPPING_LIST_ID)
);